
CREATE TABLE "cards" (
  "id" uuid PRIMARY KEY,
  "name" varchar,
  "damage" float,
  "deck" boolean,
  "trade" boolean,
  "username" varchar
);

CREATE TABLE "users" (
  "username" varchar PRIMARY KEY,
  "password" varchar,
  "coins" int,
  "name" varchar,
  "info" varchar,
  "image" varchar
);

CREATE TABLE "carddeck" (
  "pid" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "card1" uuid,
  "card2" uuid,
  "card3" uuid,
  "card4" uuid,
  "card5" uuid
);

CREATE TABLE "stats" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "wins" int,
  "losses" int,
  "elo" int,
  "username" varchar
);

CREATE TABLE "trade" (
  "id" uuid PRIMARY KEY,
  "tradingcard" uuid,
  "type" varchar,
  "mindamage" float
);

ALTER TABLE "cards" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "carddeck" ADD FOREIGN KEY ("card1") REFERENCES "cards" ("id");

ALTER TABLE "carddeck" ADD FOREIGN KEY ("card2") REFERENCES "cards" ("id");

ALTER TABLE "carddeck" ADD FOREIGN KEY ("card3") REFERENCES "cards" ("id");

ALTER TABLE "carddeck" ADD FOREIGN KEY ("card4") REFERENCES "cards" ("id");

ALTER TABLE "carddeck" ADD FOREIGN KEY ("card5") REFERENCES "cards" ("id");

ALTER TABLE "stats" ADD FOREIGN KEY ("username") REFERENCES "users" ("username");

ALTER TABLE "trade" ADD FOREIGN KEY ("tradingcard") REFERENCES "cards" ("id");
